import {EmployeeListApiRes} from '../src/interface/employee.interface';

export const employeeListApiMock: EmployeeListApiRes = {
  statusCode: '200',
  message: 'Employees retrieved successfully.',
  data: {
    isLoading: false,
    isError: false,
    content: [
      {
        id: 12,
        firstName: 'John2532',
        lastName: 'Doe1',
        email: 'john.doe1@gmail.com',
        department: 'Engineering',
        salary: 100.0,
      },
      {
        id: 18,
        firstName: 'Johnz',
        lastName: 'Doe1',
        email: 'john.doe1@gmail.com',
        department: 'Engineering',
        salary: 100.0,
      },
      {
        id: 10,
        firstName: 'John1',
        lastName: 'Doe11',
        email: 'john.doe1@gmail.com',
        department: 'Engineering',
        salary: 100.1,
      },
      {
        id: 25,
        firstName: 'Johns',
        lastName: 'Doe1',
        email: 'john.doe1@gmail.com',
        department: 'Engineering',
        salary: 100.0,
      },
      {
        id: 26,
        firstName: 'John1zzzz',
        lastName: 'Doe1',
        email: 'john.doe1@gmail.com',
        department: 'Engineering',
        salary: 100.0,
      },
      {
        id: 27,
        firstName: 'JohnSSSS',
        lastName: 'Doe1',
        email: 'john.doe1@gmail.com',
        department: 'Engineering',
        salary: 100.0,
      },
      {
        id: 33,
        firstName: 'Newfiii',
        lastName: 'Newl',
        email: 'newemail@example.com',
        department: 'My Department',
        salary: 1000.0,
      },
      {
        id: 28,
        firstName: 'John111',
        lastName: 'Doe1',
        email: 'john.doe1@gmail.com',
        department: 'Engineering',
        salary: 100.0,
      },
      {
        id: 29,
        firstName: 'John16666',
        lastName: 'Doe1',
        email: 'john.doe1@gmail.com',
        department: 'Engineering',
        salary: 100.0,
      },
      {
        id: 30,
        firstName: 'John15555',
        lastName: 'Doe1s',
        email: 'john.doe1@gmail.com',
        department: 'Engineering',
        salary: 100.0,
      },
    ],
    pageable: {
      pageNumber: 0,
      pageSize: 10,
      sort: {
        empty: true,
        sorted: false,
        unsorted: true,
      },
      offset: 0,
      paged: true,
      unpaged: false,
    },
    totalElements: 19,
    totalPages: 2,
    last: false,
    size: 10,
    number: 0,
    sort: {
      empty: true,
      sorted: false,
      unsorted: true,
    },
    numberOfElements: 10,
    first: true,
    empty: false,
  },
};
